[workspace]
members = [
    "crates/codora",
    # Adapter
    # "crates/adapter/*",
    # Internal crate mean't for internal used 
    "crates/___private/*",
    # Codora Web
    "crates/web/*",
]
resolver = "2"


[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/getcodora/codora"
keywords = ["web", "server", "orm", "authentication", "security", "logging"]
categories = ["web-programming", "web-framework", "orm"]
authors = ["West Sheriff <west.sh.mail@gmail.com>"]

[workspace.dependencies]
# Workspace Crates
codora = { path = "./crates/codora" }
codora-core = { path = "./crates/___private/codora-core" }
codora-security = { path = "./crates/web/security" }
# Adapter Crates


# External Crates
anyhow = "1.0.87"
serde = "1.0.215"
serde_json = "1.0.140"
tokio = { version = "1.44.0" }

[workspace.lints.clippy]

# TODO
# Setup Compiler Profile
