[package]
name = "weekend"
version = "0.1.0"
edition = "2021"


[features]

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
tower-layer = "0.3.3"
anyhow.workspace = true
tokio = { version = "1.44.0", features = ["full"] }

[dev-dependencies]
tokio = { version = "1.44.0", features = ["full"] }


[workspace]
members = [
  # core crates for weekend-rs authentication and authorization
  ".",
  "crates/*",
]
resolver = "2"


[workspace.lints.clippy]
disallowed_methods = 'deny'

[workspace.package]
version = "0.8.3"
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/theProject-org/weekend"
# TODO Add other important keyword!
keywords = ["authentication", "authorization", "weekend", "weekend-rs"]
categories = ["web-programming", "security", "authentication", "authorization"]
authors = ["West Sheriff <west.sh.mail@gmail.com>"]

[workspace.dependencies]
anyhow = "1.0.87"
async-trait = "0.1.83"
serde = "1.0.215"
plus-rs = { git = "https://github.com/ws-gith/plus.git", rev = "462ad8feabc57a4cfeded89c7544ee8b4eaee858" }
