[workspace]
members = [
  #  core crates for weekend-rs authentication and authorization
  "security",
  "security/bearer",
  "security/cookie",
  "security/jwt",
  "security/oauth", 
  
  # iam crates 
  "iam", 
  
  # adapter crates - these are set of libraries that allow weekend-rs to work with external resources or framework's
  "adapters",
  "adapters/actix",
  "adapters/axum",
  "adapters/mysql",
  "adapters/postgres",
]


resolver = "2"

[workspace.dependencies]
anyhow = "1.0.87"
async-trait = "0.1.83"
serde = "1.0.215"
plus = { git = "https://github.com/theProjectNG/plus.git", rev = "e23ce82ecef33ba857e29d1e82ddd2fe9069d762" }
