[package]
name = "codora-bot"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
derive-new = "0.7.0"

[lints]
workspace = true
