[package]
name = "codora-proc-macro"
version = "0.1.0"
edition.workspace = true

[features]
default = ["conf"]
conf = []

[lib]
proc-macro = true


[dependencies]
darling = "0.21.3"
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = "2.0.106"

[lints]
workspace = true
