[package]
name = "codora"
version = { workspace = true }
edition = { workspace = true }


[features]
core = ["dep:codora-core"]
default = ["core", "security"]
security = ["dep:codora-security"]


[dependencies]
codora-core = { workspace = true, optional = true }
codora-security = { workspace = true, optional = true }


[dev-dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
