[package]
name = "codora"
version = { workspace = true }
edition = { workspace = true }


[features]
default = ["util", "security"]
validator = ["dep:codora-validator"]
security = ["dep:codora-security"]
util = ["dep:codora-util"]
axum = ["dep:codora-adapter-axum"]


[dependencies]
codora-util = { workspace = true, optional = true }
codora-security = { workspace = true, optional = true }
codora-validator = { workspace = true, optional = true }
codora-adapter-axum = { workspace = true, optional = true }

[dev-dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
