[package]
name = "weekend"
version = "0.1.0"
edition = "2021"


[features]
default = ['authentication', "authorization"]
authentication = []
authorization = []

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
tower-layer = "0.3.3"
